export const testDataChats = [
    {
        id: 1,
        name: 'Anna',
        lastMessage: 'asap',
        timeStamp: '06:03 PM',
        online: true,
    },
    {
        id: 2,
        name: 'Anna',
        lastMessage: 'asap djdj d fkdjgjbdvf ff f if f fdf i',
        timeStamp: '01:03 PM',
        online: false,
    },
    {
        id: 3,
        name: 'Jordan',
        lastMessage: 'asap',
        timeStamp: '12:03 PM',
        online: true,
    },
    {
        id: 4,
        name: 'Anna',
        lastMessage: 'afsdf fdsf ds ! ds ds d???? >?d sdsap',
        timeStamp: '12:03 PM',
        online: false,
    },
    {
        id: 5,
        name: 'Aser',
        lastMessage: 'asap',
        timeStamp: '12:03 PM',
        online: true,
    },
    {
        id: 1,
        name: 'Anna',
        lastMessage: 'asap',
        timeStamp: '06:03 PM',
        online: true,
    },
    {
        id: 2,
        name: 'Anna',
        lastMessage: 'asap djdj d fkdjgjbdvf ff f if f fdf i',
        timeStamp: '01:03 PM',
        online: false,
    },
    {
        id: 3,
        name: 'Jordan',
        lastMessage: 'asap',
        timeStamp: '12:03 PM',
        online: true,
    },
    {
        id: 4,
        name: 'Anna',
        lastMessage: 'afsdf fdsf ds ! ds ds d???? >?d sdsap',
        timeStamp: '12:03 PM',
        online: false,
    },
    {
        id: 5,
        name: 'Aser',
        lastMessage: 'asap',
        timeStamp: '12:03 PM',
        online: true,
    },
];
